### ISSUE TITLE
Cannot read property 'cells' of null

### ISSUE THREAD

**Issue by fretha** [Andries-Smit/TabExtension#5]
Great widget - just what I was looking for. Unfortuantely I get this error when using the ButtonTab

Could not create widget TabExtension.TabButton: TypeError: Cannot read property 'cells' of null

Any guidance? (Using 6.5.1)

Thanks Fredrik

**Comment by Andries-Smit** [comment]
Hi Fetha,

I think the issue is caused the position of the widget inside the page. You need to place the tab in a table, and the widget inside the cell just below. 

This way is a bit old fashion, as we have some better ways with with grid layouts.

Please try if this solves your issue.

I might add a better way of selecting the widget at a later stage.

Cheers.

**Comment by fretha** [comment]
it worked thanks. Any way to trigger a microflow when selecting a tab?

**Comment by Andries-Smit** [comment]
not yet! not soon. If you like you can make it and send me a pull request.

2016-09-16 10:55 GMT+02:00 fretha <notifications@github.com>:

**Comment by Andries-Smit** [comment]
Config issue, with new release, you place the widget anywhere, you just need to select the target name.
